# Generated by Django 6.0.3 on 2026-03-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='activity',
            name='category',
            field=models.CharField(choices=[('Faculty Development', 'Faculty Development'), ('Research', 'Research'), ('Student Activity', 'Student Activity')], max_length=100),
        ),
        migrations.AlterField(
            model_name='activity',
            name='data_json',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='activity',
            name='department',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('CSE', 'Computer Science & Engineering'), ('AIML', 'AI & Machine Learning'), ('AIDS', 'AI & Data Science'), ('Auto', 'Automobile Engineering'), ('Mech', 'Mechanical Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('ACT', 'Applied Computer Technology (MCA)'), ('VLSI', 'VLSI Design'), ('Cyber', 'Cyber Security')], default='IT', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(choices=[('IT', 'Information Technology'), ('CSE', 'Computer Science & Engineering'), ('AIML', 'AI & Machine Learning'), ('AIDS', 'AI & Data Science'), ('Auto', 'Automobile Engineering'), ('Mech', 'Mechanical Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('ACT', 'Applied Computer Technology (MCA)'), ('VLSI', 'VLSI Design'), ('Cyber', 'Cyber Security')], default='IT', max_length=20),
        ),
    ]
