# Generated by Django 6.0.3 on 2026-03-26 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_system', '0002_alter_activity_options_user_full_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('IT', 'Information Technology'), ('CSE', 'Computer Science & Engineering'), ('AIML', 'AI & Machine Learning'), ('AIDS', 'AI & Data Science'), ('Auto', 'Automobile Engineering'), ('Mech', 'Mechanical Engineering'), ('EEE', 'Electrical & Electronics Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('ACT', 'Applied Computer Technology (MCA)'), ('VLSI', 'VLSI Design'), ('Cyber', 'Cyber Security')], max_length=20)),
                ('academic_year', models.CharField(max_length=20)),
                ('sheet_name', models.CharField(max_length=255)),
                ('target_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('department', 'academic_year', 'sheet_name')},
            },
        ),
        migrations.CreateModel(
            name='FacultyTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_year', models.CharField(max_length=20)),
                ('sheet_name', models.CharField(max_length=255)),
                ('target_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('faculty', 'academic_year', 'sheet_name')},
            },
        ),
    ]
