# Generated by Django 6.0.3 on 2026-03-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_system', '0003_departmenttarget_facultytarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='requires_od',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('OD_PENDING', 'Pending OD (SPOC)'), ('OD_SPOC_APPROVED', 'Pending OD (HOD)'), ('OD_APPROVED', 'OD Approved (Awaiting Proof)'), ('PENDING', 'Pending'), ('SPOC_APPROVED', 'SPOC Approved'), ('HOD_APPROVED', 'HOD Approved'), ('IQAC_APPROVED', 'IQAC Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
