# Generated by Django 6.0.3 on 2026-04-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_system', '0004_activity_requires_od_alter_activity_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='department',
            field=models.CharField(default='IT', max_length=50),
        ),
        migrations.AlterField(
            model_name='departmenttarget',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(default='IT', max_length=50),
        ),
    ]
