# Generated by Django 6.0.3 on 2026-04-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_system', '0005_department_alter_activity_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmenttarget',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='facultytarget',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
