# Generated by Django 6.0.3 on 2026-04-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_system', '0006_departmenttarget_points_facultytarget_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='point_claimed',
            field=models.BooleanField(default=False),
        ),
    ]
