# Generated by Django 6.0.3 on 2026-04-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_system', '0007_activity_point_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.FileField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
