# Generated by Django 6.0.3 on 2026-04-08 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_system', '0008_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='awarded_points',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
