# Generated by Django 6.0.3 on 2026-04-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_system', '0009_activity_awarded_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(choices=[('AP', 'Assistant Professor'), ('AP_SS', 'Assistant Professor (SS)'), ('AP_SG', 'Assistant Professor (SG)'), ('ASP', 'Associate Professor'), ('PROF', 'Professor'), ('OTHER', 'Other / N/A')], default='AP', max_length=20),
        ),
    ]
