# Generated by Django 6.0.3 on 2026-04-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_system', '0010_user_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cadre',
            field=models.CharField(blank=True, choices=[('Professor', 'Professor'), ('Associate Professor', 'Associate Professor'), ('Assistant Professor (SG)', 'Assistant Professor (SG)'), ('Assistant Professor (SS)', 'Assistant Professor (SS)'), ('Assistant Professor', 'Assistant Professor')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_dashboard_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
