# Generated by Django 6.0.3 on 2026-04-09 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_system', '0011_user_cadre_user_last_dashboard_check_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_dashboard_check',
        ),
        migrations.AlterField(
            model_name='activity',
            name='awarded_points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='cadre',
            field=models.CharField(blank=True, choices=[('Assistant Professor', 'Assistant Professor'), ('Assistant Professor (SS)', 'Assistant Professor (SS)'), ('Assistant Professor (SG)', 'Assistant Professor (SG)'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], max_length=50, null=True),
        ),
    ]
