# Generated by Django 4.2.30 on 2026-04-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_system', '0012_remove_user_designation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cadre',
            field=models.CharField(blank=True, choices=[('Assistant Professor', 'Assistant Professor'), ('Assistant Professor (SS)', 'Assistant Professor (SS)'), ('Assistant professor(SG)', 'Assistant professor(SG)'), ('Associate Professor', 'Associate Professor'), ('Professor', 'Professor')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('FACULTY', 'Faculty'), ('SPOC', 'SPOC'), ('HOD', 'HOD'), ('PC', 'PC'), ('IQAC', 'IQAC')], default='FACULTY', max_length=20),
        ),
    ]
